org.gradle.jvmargs=-Xmx3g -Xss8m -Dfile.encoding=UTF-8
org.gradle.caching=true
org.gradle.parallel=true
kotlin.code.style=official
android.useAndroidX=true
android.nonTransitiveRClass=true
android.suppressUnsupportedCompileSdk=35
kotlin.mpp.enableCInteropCommonization=true
kotlin.native.ignoreDisabledTargets=true
